<Project>
  <PropertyGroup>
    <BaseOutputPath>build\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>build\obj\</BaseIntermediateOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
</Project>